config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators, controllers: {
    sessions:      'administrators/sessions',
    passwords:     'administrators/passwords',
    registrations: 'administrators/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  get 'saunas/index'
 root to: "saunas#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Saunner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>

           <% if user_signed_in? %>
             <div class="nav__right"> 
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
             </div>
            <% elsif administrator_signed_in? %>
            <div class="nav__right"> 
              <%= link_to "ログアウト", destroy_administrator_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "サウナ情報登録", root_path, class: :nav__btn %>
            </div>  
           <% else %>
             <div class="nav__right1">
              <%= link_to "ユーザーログイン", new_user_session_path, class: :nav__btn1 %>
              <%= link_to "ユーザー新規登録", new_user_registration_path, class: :nav__btn1 %>
             </div>
             <div class="nav__right2">
              <%= link_to "サウナ店舗ログイン", new_administrator_session_path, class: :nav__btn2 %>
              <%= link_to "サウナ店舗新規登録", new_administrator_registration_path, class: :nav__btn2 %>
            </div>
           <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>